function f=nbidata(file)

  ## -- F = nbisurf(FILE)
  ##
  ## Read data from an NBI data file
  ##
  ## FILE is the name of an NBI data file, such as one generated by
  ## nbi-solve-laplace, nbi-solve-helmholtz, nbi-field-laplace, or
  ## nbi-field-helmholtz
  ##
  ## F: matrix of surface data, one row per surface node

  fid = fopen(file, "r") ;

  ## clear the ASCII header data
  fscanf(fid, "%c", 40) ;
  dat = fscanf(fid, "%d", 2) ;
  ## number of data entries per node, number of nodes
  ndat = dat(1) ; nnodes = dat(2) ;

  f = fscanf(fid, "%f", ndat*nnodes) ;

  f = reshape(f, ndat, nnodes)' ;

  fclose(fid) ;
