function p=sphpot(a, x, y, z)

  ## P = SPHPOT(a, x, y, z)
  ##
  ## Evaluate potential about a sphere in uniform flow in the +z
  ##direction
  ##
  ## a:       sphere radius (x,y,z): position
  ##
  ## Potential is evaluated as (a/r)^3*z/2, which is the potential
  ## generated by the sphere subject to a unit velocity in +z
  ## direction. The total potential in the field for velocity U is
  ## given by Uz + U*sphpot(a, x, y, z)

  r = sqrt(x.^2 + y.^2 + z.^2) ;
  p = z/2.*(a./r).^3 ;
  
  
