#!/bin/bash

a=0.7
Mt=1.1
n=4

nqa=54
nqp=25
nqu=54
tol=1e-6
eta=1.5
depth=2
order=8
nthreads=4

k=`echo ${n}*${Mt}/${a} | bc -l`
echo wavenumber: ${k}

bin=../../tools

gfile=Geometries/nacelle-${nqp}.nbi
mfile=Matrices/matrix-nacelle-helmholtz-${nqp}-${nqu}-${order}-${depth}.dat

opts="-e ${tol} -a ${nqa} -u ${nqu} \
      -n ${eta} -d ${depth} -N ${order} \
      -m ${mfile} -g ${gfile} -k ${k}"
echo -- ${opts}

${bin}/nbi-surface -q ${nqp} -g ellipsoid-ico -i 3 -d 0.5 -d 0.5 -d 1 -o ${gfile}

${bin}/nbi-assemble-helmholtz ${opts} -T ${nthreads}

#opts="-m ${mfile} -g ${gfile} -D 5 -o 10 -d 2 -t 1e-6 \
#      -f -T ${nthreads} -K ksp-options \
#      -k ${k} -b pcsource.bc -s solution.dat"
#echo ${opts}

## solve with ring source modelling rotor
${bin}/nbi-solve-helmholtz -m ${mfile} -g ${gfile} -D 5 -o 10 -d 2 -t 1e-6 \
      -f -T ${nthreads} -K ksp-options -P \
      -k ${k} -b ring.bc -s solution.dat

## generate radiated field on 33x33 grid in plane z=-0.5, -2 < x, y < 2
${bin}/nbi-surface -g grid-xy -d -2 -d -2 -d 2 -d 2 -d -0.5 \
      -i 65 -i 65 > grid.nbi
${bin}/nbi-field-helmholtz -g ${gfile} -d solution.dat \
      -k ${k} -F grid.nbi -b ring.bc > grid.dat
## generate gmsh file for visualization
${bin}/nbi-process -d grid.dat -g grid.nbi -r 2 > grid.msh 2> log

## extract the indices of the last point and element
offp=`grep point: log | cut -d: -f2`
offe=`grep element: log | cut -d: -f2`

## nacelle surface pressure
${bin}/nbi-field-helmholtz -g ${gfile} -d solution.dat \
      -S -k ${k} -b ring.bc > surface.dat
## start numbering this mesh from the last indices of the previous one
${bin}/nbi-process -d surface.dat -g ${gfile} -r 1 \
      -e ${offe} -p ${offp} > nacelle.msh 2> log

## extract the indices of the last point and element
offp=`grep point: log | cut -d: -f2`
offe=`grep element: log | cut -d: -f2`

## a tube wrapped round the nacelle to see the near field
${bin}/nbi-surface -q 25 -m tube.geo > tube.nbi
${bin}/nbi-field-helmholtz -g ${gfile} -d solution.dat \
      -F tube.nbi -k ${k} -b ring.bc > tube.dat
${bin}/nbi-process -d tube.dat -g tube.nbi -r 1 \
      -e ${offe} -p ${offp} > tube.msh 2> log

