#!/bin/bash

nqa=25
nqp=7
nqu=25
tol=1e-6
eta=1.5
depth=4
order=8
nthreads=2
k=3.5
src=pcsource.bc

## path to executables
bin=../../tools

## store geometry and matrix data in subdirectories
gfile=Geometries/wing-${nqp}.nbi
mfile=Matrices/matrix-wing-${nqp}-${nqu}-${order}-${depth}-${k}.dat

## generate the surface
${bin}/nbi-surface -q ${nqp} -a wing.agg -o ${gfile}

## generate an option list for nbi-assemble-helmholtz and display it
opts="-e ${tol} -a ${nqa} -u ${nqu} -n ${eta} -d ${depth} -N ${order} \
      -m ${mfile} -g ${gfile} -k ${k}"
echo nbi-assemble-helmholtz ${opts}
## assemble the problem matrices
${bin}/nbi-assemble-helmholtz ${opts} -T ${nthreads}

## solve the problem
opts="-m ${mfile} -g ${gfile} -D 4 -o 10 -d 2 -t 1e-3 -k ${k} \
      -P -K ksp-options \
      -r 50 -f -T ${nthreads} -b ${src} -s solution.dat"
echo nbi-solve-helmholtz ${opts}
${bin}/nbi-solve-helmholtz ${opts}

## radiated field
${bin}/nbi-surface -g grid-yz -d -4 -d -4 -d 4 -d 4 -d -1 \
      -i 33 -i 33 > grid.nbi
## field radiated by surface solution
${bin}/nbi-field-helmholtz -g ${gfile} -d solution.dat \
      -k ${k} -F grid.nbi > grid.dat
${bin}/nbi-process -d grid.dat -g grid.nbi -r 2 > grid.msh
