Surfaces
Generating, discretizing and manipulating NBI surfaces.
Functions
 nbi_surface_t * nbi_surface_alloc (gint nnmax, gint npmax)
allocate an nbi_surface_t
gint nbi_surface_write (nbi_surface_t *s, FILE *f)
write an nbi_surface_t to file
 nbi_surface_t * nbi_surface_read (FILE *f)
allocate and read an nbi_surface_t from file
gint nbi_surface_patch_centroid (gdouble *x, gint xstr, gdouble *w, gint wstr, gint nx, gdouble *c)
estimate centroid of surface patch
gdouble nbi_surface_patch_radius (gdouble *x, gint xstr, gint nx, gdouble *c)
estimate radius of circumsphere of surface patch
gint nbi_patch_neighbours (gdouble *c, gdouble r, gdouble *x, gint xstr, gint nx, gint n0, gint n1, gint *nbrs, gint *nnbrs, gint nnmax)
identify neighbour nodes of surface patch
gint nbi_surface_patch_neighbours (nbi_surface_t *s, gint p, gdouble r, gint *nbrs, gint *nnbrs, gint nnmax)
identify neighbours of a surface patch
gint nbi_element_interp_matrix (gint ns, gdouble **K, gint *Nk)
Koornwinder interpolation matrix for surface patch.
gdouble * nbi_patch_upsample_matrix (gint ns, gint nu)
matrix for upsampling patch nodes to quadrature nodes
gint nbi_surface_set_patch_data (nbi_surface_t *s)
set basic data (centroid and radius) for each patch of a surface.
gint nbi_geometry_sphere (nbi_surface_t *s, gdouble r, gint nth, gint nph, gint nq)
gint nbi_geometry_ellipsoid (nbi_surface_t *s, gdouble a, gdouble b, gdouble c, gint nth, gint nph, gint nq)
gint nbi_geometry_sphere_ico (nbi_surface_t *s, gdouble r, gint nr, gint nq)
gint nbi_geometry_ellipsoid_ico (nbi_surface_t *s, gdouble a, gdouble b, gdouble c, gint nr, gint nq)
gint nbi_geometry_grid (nbi_surface_t *s, gdouble smin, gdouble smax, gint ns, gdouble tmin, gdouble tmax, gint nt, gint nq)
 nbi_surface_t * nbi_gmsh_mesh (gchar *file, gint nq)
typedef nbi_surface_t
Detailed Description
Generating, discretizing and manipulating NBI surfaces.
NBI represents surfaces as triangular patches which are mapped using Koornwinder orthogonal polynomials, giving a high order representation of the surface and of the potential on it. Surface points are placed at the nodes of high order quadrature rules for the unit triangle, and interpolation of surface quantities, including position, is performed using the Koornwinder polynomials.
A surface patch takes two discretization parameters. The first is the number of nodes on the patch. These are the points where the solution will be found when the problem is solved subject to a given set of boundary conditions. The second parameter is the number of upsampled nodes. In order to evaluate the surface integrals in the problem, the estimated solution is interpolated, or upsampled, onto a set of nodes on each patch, giving a more refined discretization for evaluation of the potential integrals. The number of upsampled nodes should be at least equal to the number of nodes in the patch discretization.
Surfaces can be generated using the built-in geometries in NBI (a list is available using the -G option of nbi-surface); a GMSH .geo file; or an AGG file https://github.com/mjcarley/agg/ which uses the geometric representation methods of Kulfan, https://www.brendakulfan.com/research
Built-in geometries are quite simple but are sufficient for testing of code and checking the toolchain. There are also grid geometries which are not intended for calculation but are suitable for visualising the potential field around surfaces after a problem has been solved.
Function Documentation
nbi_element_interp_matrix()
gint nbi_element_interp_matrix (gint ns, gdouble ** K, gint * Nk)
Koornwinder interpolation matrix for surface patch.
Parameters
ns number of interpolation nodes on patch;
K on exit, pointer to interpolation matrix for patch;
Nk on exit, maximum order of Koornwinder polynomial in interpolation.
Returns
0 on success.
Referenced by nbi_patch_upsample_matrix().
nbi_geometry_ellipsoid()
gint nbi_geometry_ellipsoid (nbi_surface_t * s, gdouble a, gdouble b, gdouble c, gint nth, gint nph, gint nq)
Generate an ellipsoidal surface
Parameters
s surface to which patches are to be added;
a ellipsoid length on $x$ axis;
b ellipsoid length on $y$ axis;
c ellipsoid length on $z$ axis;
nth number of patches in azimuth $\theta$;
nph number of patches in elevation $\phi$;
nq number of quadrature points per patch.
Returns
0 on success.
nbi_geometry_ellipsoid_ico()
gint nbi_geometry_ellipsoid_ico (nbi_surface_t * s, gdouble a, gdouble b, gdouble c, gint nr, gint nq)
Generate an ellipsoidal surface by recursive subvision of a deformed icosahedron
Parameters
s surface to which patches are to be added;
a ellipsoid length on $x$ axis;
b ellipsoid length on $y$ axis;
c ellipsoid length on $z$ axis;
nr number of subdivisions;
nq number of quadrature points per patch.
Returns
0 on success.
nbi_geometry_grid()
gint nbi_geometry_grid (nbi_surface_t * s, gdouble smin, gdouble smax, gint ns, gdouble tmin, gdouble tmax, gint nt, gint nq)
Generate a regular grid in plane $z=0$ which can be transformed and used for visualisation. Nodes are interpolated between $(s_{\min},t_{\min},0)$ and $(s_{\max},t_{\max},0)$
Parameters
s surface to add patches to;
smin coordinate of lower left corner of grid;
smax coordinate of upper right corner of grid;
ns number of nodes in $s$.
tmin coordinate of lower left corner of grid;
tmax coordinate of upper right corner of grid;
nt number of nodes in $t$.
nq number of quadrature nodes per patch on s.
Returns
0 on succes.
nbi_geometry_sphere()
gint nbi_geometry_sphere (nbi_surface_t * s, gdouble r, gint nth, gint nph, gint nq)
Generate a spherical surface
Parameters
s surface to which sphere patches are to be added;
r radius of sphere;
nth number of patches in azimuth $\theta$;
nph number of patches in elevation $\phi$;
nq number of quadrature points per patch.
Returns
0 on success.
nbi_geometry_sphere_ico()
gint nbi_geometry_sphere_ico (nbi_surface_t * s, gdouble r, gint nr, gint nq)
Generate a spherical surface by recursive subdivision of an icosahedron
Parameters
s surface to which sphere patches are to be added;
r radius of sphere;
nr number of subdivisions;
nq number of quadrature points per patch.
Returns
0 on success.
nbi_gmsh_mesh()
 nbi_surface_t * nbi_gmsh_mesh (gchar * file, gint nq)
Generate an nbi_surface_t from a GMSH .geo file (experimental, but has been reliable up to now)
Parameters
file name of GMSH file;
nq number of quadrature points per patch.
Returns
pointer to newly allocated nbi_surface_t containing surface generated from file.
References nbi_surface_alloc(), and nbi_surface_t.
nbi_patch_neighbours()
gint nbi_patch_neighbours (gdouble * c, gdouble r, gdouble * x, gint xstr, gint nx, gint n0, gint n1, gint * nbrs, gint * nnbrs, gint nnmax)
identify neighbour nodes of surface patch
Parameters
c centroid;
r radius of neighbourhood;
x list of candidate neighbour nodes;
xstr stride from first component of one node to first component of next;
nx number of candidate neighbour nodes;
n0 first entry in x to check;
n1 last entry in x to check;
nbrs on exit contains indices of nodes lying within distance r of c;
nnbrs on exit contains number of nodes in nbrs;
nnmax maximum number of neighbours to be inserted in nbrs.
Returns
0 on success.
nbi_patch_upsample_matrix()
gdouble * nbi_patch_upsample_matrix (gint ns, gint nu)
matrix for upsampling patch nodes to quadrature nodes
Parameters
ns number of patch nodes (must match an available quadrature rule);
nu number of upsampled nodes (must match an available quadrature rule).
Returns
pointer to upsampling matrix.
References nbi_element_interp_matrix().
nbi_surface_alloc()
 nbi_surface_t * nbi_surface_alloc (gint nnmax, gint npmax)
allocate an nbi_surface_t
Parameters
nnmax maximum number of nodes in surface;
npmax maximum number of patches in surface.
Returns
pointer to newly allocated nbi_surface_t
References nbi_surface_node_number, nbi_surface_node_number_max, nbi_surface_patch_number, nbi_surface_patch_number_max, and nbi_surface_t.
Referenced by nbi_gmsh_mesh().
nbi_surface_patch_centroid()
gint nbi_surface_patch_centroid (gdouble * x, gint xstr, gdouble * w, gint wstr, gint nx, gdouble * c)
estimate centroid of surface patch
Parameters
x coordinates of patch nodes;
xstr stride from first component of one to first component of next;
w patch quadrature weights;
wstr quadrature weight stride;
nx number of nodes;
c on exit contains coordinates of centroid.
Returns
0 on success.
Referenced by nbi_surface_set_patch_data().
nbi_surface_patch_neighbours()
gint nbi_surface_patch_neighbours (nbi_surface_t * s, gint p, gdouble r, gint * nbrs, gint * nnbrs, gint nnmax)
identify neighbours of a surface patch
Parameters
s an nbi_surface_t;
p index of patch whose neighbours are to be found;
r radius of neighbourhood;
nbrs on exit contains indices of nodes of s lying with distance r of centroid of patch p of s;
nnbrs on exit contains number of entries in nbrs;
nnmax limit on number of entries in nbrs.
Returns
0 on success.
nbi_surface_patch_radius()
gdouble nbi_surface_patch_radius (gdouble * x, gint xstr, gint nx, gdouble * c)
estimate radius of circumsphere of surface patch
Parameters
x coordinates of patch nodes;
xstr stride from first component of one node to first component of next;
nx number of patch nodes;
c centroid of patch (from nbi_surface_patch_centroid)).
Returns
patch radius
nbi_surface_read()
 nbi_surface_t * nbi_surface_read (FILE * f)
allocate and read an nbi_surface_t from file
Parameters
f input file stream.
Returns
pointer to newly allocated surface, read from file
References nbi_surface_t.
nbi_surface_set_patch_data()
gint nbi_surface_set_patch_data (nbi_surface_t * s)
set basic data (centroid and radius) for each patch of a surface.
Parameters
s an nbi_surface_t whose data are to be set.
Returns
0 on success
References nbi_surface_node, nbi_surface_node_weight, nbi_surface_patch_centre, nbi_surface_patch_centroid(), nbi_surface_patch_node, nbi_surface_patch_node_number, nbi_surface_patch_number, and nbi_surface_patch_sphere_radius.
nbi_surface_write()
gint nbi_surface_write (nbi_surface_t * s, FILE * f)
write an nbi_surface_t to file
Parameters
s surface to write to file
f output file stream
Returns
0 on success
Variable Documentation
nbi_surface_t
nbi_surface_t
Basic data type for NBI surfaces, including element and quadrature information
Referenced by nbi_gmsh_mesh(), nbi_surface_alloc(), and nbi_surface_read().