#!/bin/bash

nqa=25
nqp=7
nqu=25
tol=1e-6
eta=1.5
depth=3
order=8
nthreads=4

bin=../../tools

gfile=Geometries/sphere-${nqp}.dat
mfile=Matrices/matrix-sphere-${nqp}-${nqu}-${order}-${depth}.dat

opts="-e ${tol} -a ${nqa} -u ${nqu} \
      -n ${eta} -d ${depth} -N ${order} \
      -m ${mfile} -g ${gfile}"
echo -- ${opts}

${bin}/nbi-surface -q ${nqp} -a sphere.agg -o ${gfile}

${bin}/nbi-assemble-laplace ${opts} -T ${nthreads}


opts="-m ${mfile} -g ${gfile} -D 5 -o 10 -d 2 -t ${tol} \
      -f -T ${nthreads} \
      -b psource.bc -s sphere-field.dat"

echo ${opts}

${bin}/nbi-solve-laplace ${opts}

## -P -K ksp-options \
