#!/bin/bash

k=4.435
nqa=7
nqp=7
nqu=25
tol=1e-6
eta=1.25
depth=4
order=8
nthreads=2

## path to executables
bin=../../tools
## boundary condition
bcfile=pcsource.bc
#bcfile=ring.bc

## store geometry and matrix data in subdirectories
##gfile=Geometries/sphere-${nqp}.nbi
##mfile=Matrices/matrix-sphere-helmholtz-${nqp}-${nqu}-${order}-${depth}.dat
gfile=Geometries/aircraft-${nqp}.nbi
mfile=Matrices/matrix-aircraft-helmholtz-${nqp}-${nqu}-${order}-${depth}.dat

## generate the spherical surface using the internal geometry generator
##${bin}/nbi-surface -q ${nqp} -g ellipsoid-ico -i 2 -d 1 -d 1 -d 1 -o ${gfile}
#${bin}/nbi-surface -q ${nqp} -a sphere.agg -o ${gfile}
${bin}/nbi-surface -q ${nqp} -a aircraft.agg -o ${gfile}

opts="-e ${tol} -a ${nqa} -u ${nqu} \
      -n ${eta} -d ${depth} -N ${order} \
      -m ${mfile} -g ${gfile} -k ${k}"
echo -- ${opts}

## assemble the problem matrices
${bin}/nbi-assemble-helmholtz ${opts} -T ${nthreads}

opts="-m ${mfile} -g ${gfile} -D 5 -o 10 -d 2 -t 1e-6 \
      -f -T ${nthreads} -K ksp-options \
      -k ${k} -b ${bcfile} -s solution.dat "
echo ${opts}

## solve with specified boundary condition
${bin}/nbi-solve-helmholtz -m ${mfile} -g ${gfile} -D 5 -o 4 -d 2 -t 1e-3 \
      -f -T ${nthreads} -K ksp-options -P \
      -k ${k} -b ${bcfile} -s solution.dat

#${bin}/nbi-solve-helmholtz -m ${mfile} -g ${gfile} -D 4 -o 4 -d 4 -t 1e-3 \
#      -f -T ${nthreads} -K ksp-options -P \
#      -k ${k} -b ${bcfile} -I -s layer.dat

##-K ksp-options -P \

## generate radiated field on 33x33 grid in plane z=2.5, -2 < x, y < 2
#${bin}/nbi-surface -g grid-xy -d -2 -d -2 -d 2 -d 2 -d 2.5 \
#      -i 33 -i 33 > grid.nbi
${bin}/nbi-surface -g grid-yz -d -4 -d -4 -d 4 -d 4 -d -1 \
      -i 33 -i 33 > grid.nbi
## field radiated by surface solution
${bin}/nbi-field-helmholtz -g ${gfile} -d solution.dat \
      -k ${k} -F grid.nbi > grid.dat
## adding the incident term gives total field
${bin}/nbi-field-helmholtz -g ${gfile} -d solution.dat \
      -k ${k} -F grid.nbi -b ${bcfile} > total.dat
## generate gmsh files for visualization
#${bin}/nbi-process -d grid.dat -g grid.nbi -r 2 > grid.msh
${bin}/nbi-process -d total.dat -g grid.nbi -r 2 > total.msh
