#!/bin/bash

logfile=test-helmholtz.log
normfile=test-helmholtz-norm.log
rm -f ${logfile} ${normfile}

## scattering of a plane wave
k=10
nqp=25
nqu=54
echo Scattering test k=${k} nqp=${nqp} nqu=${nqu} >> ${logfile}
echo Scattering test k=${k} nqp=${nqp} nqu=${nqu} >> ${normfile}
cd Scattering
../solve-helmholtz -k ${k} -p ${nqp} -u ${nqu} -s plane.bc -P &>> ../${logfile}
echo Scattering test >> ../${normfile}
grep norm solution.log | grep -v KSP >> ../${normfile}
cd ..

## ring source inside sphere
k=3.5
nqp=25
nqu=54
echo SphereHelmholtz test k=${k} nqp=${nqp} nqu=${nqu} >> ${logfile}
echo SphereHelmholtz test k=${k} nqp=${nqp} nqu=${nqu} >> ${normfile}
cd SphereHelmholtz
../solve-helmholtz -k ${k} -p ${nqp} -u ${nqu} -s ring.bc &>> ../${logfile}
echo SphereHelmholtz test >> ../${normfile}
grep norm solution.log | grep -v KSP >> ../${normfile}
cd ..

## point source inside a wing 
k=3.0
nqp=25
nqu=54
echo Wing test k=${k} nqp=${nqp} nqu=${nqu} >> ${logfile}
echo Wing test k=${k} nqp=${nqp} nqu=${nqu} >> ${normfile}
cd Wing
../solve-helmholtz -k ${k} -p ${nqp} -u ${nqu} -s pcsource.bc -g wing \
     &>> ../${logfile}
echo Wing test >> ../${normfile}
grep norm solution.log | grep -v KSP  >> ../${normfile}
cd ..

## point source inside a catseye 
k=3.0
nqp=25
nqu=54
echo Catseye test k=${k} nqp=${nqp} nqu=${nqu} >> ${logfile}
echo Catseye test k=${k} nqp=${nqp} nqu=${nqu} >> ${normfile}
cd Catseye
../solve-helmholtz -k ${k} -p ${nqp} -u ${nqu} -s pcsource.bc -g catseye \
     &>> ../${logfile}
echo Catseye test >> ../${normfile}
grep norm solution.log | grep -v KSP  >> ../${normfile}
cd ..

## scattering of rotor noise by an ellipsoid
## wavenumber is calculated from source Mach number and azimuthal order
k=`echo 4*1.1/0.7 | bc -l`
nqp=25
nqu=54
echo Rotor test k=${k} nqp=${nqp} nqu=${nqu} >> ${logfile}
echo Rotor test k=${k} nqp=${nqp} nqu=${nqu} >> ${normfile}
cd Rotor
../solve-helmholtz -k ${k} -d 2 -p ${nqp} -u ${nqu} -s ring.bc -g rotor \
     &>> ../${logfile}
echo Rotor test >> ../${normfile}
grep norm solution.log | grep -v KSP  >> ../${normfile}
cd ..
