#!/bin/bash

np=8
nt=16
nqa=25
nqp=54
nqu=85
tol=1e-9
radius=1.5
eta=1.25
depth=6
order=12
ico=1

bin=../tools

gfile=ellipsoid-${np}-${nt}-${nqp}.dat
mfile=matrix-${np}-${nt}-${nqp}-${nqu}.dat

opts="-e ${tol} -a ${nqa} -u ${nqu} \
      -r ${radius} -n ${eta} -d ${depth} -N ${order} \
      -m ${mfile} -g ${gfile}"
echo -- ${opts}
${bin}/nbi-assemble-laplace ${opts}

${bin}/nbi-solve-laplace -m ${mfile} -g ${gfile} > field.dat
#${bin}/nbi-solve -f -m ${mfile} -g ${gfile} > fieldfmm.dat

## ellipsoid-8-16-54.dat matrix-8-16-54-85.dat norm: 4.64319e-05
