#!/bin/bash

nqa=25
nqp=54
nqu=85
tol=1e-12
radius=1.5
eta=1.25
depth=8
order=16
ico=3

bin=../tools

gfile=ellipsoid-ico-${ico}-${nqp}.dat
mfile=matrix-ico-${ico}-${nqp}-${nqu}-${order}-${depth}.dat

opts="-e ${tol} -a ${nqa} -q ${nqp} -u ${nqu} \
      -r ${radius} -n ${eta} -d ${depth} -N ${order} \
      -m ${mfile} -g ${gfile} -i ${ico}"
echo -- ${opts}
#${bin}/nbi-assemble ${opts}

#${bin}/nbi-solve -m ${mfile} -g ${gfile} > field.dat
${bin}/nbi-solve -f -m ${mfile} -g ${gfile} -l > fieldfmm.dat

## -g ellipsoid-ico-2-85.dat -m matrix-ico-2-85-175.dat L_inf norm: 5.83179e-07
## -g ellipsoid-ico-2-54.dat -m matrix-ico-2-54-85.dat L_inf norm: 6.97742e-07
## -g ellipsoid-ico-2-54.dat -m matrix-ico-2-54-175.dat L_inf norm: 4.79919e-07
## -g ellipsoid-ico-2-54.dat -m matrix-ico-2-54-175-16-7.dat norm: 4.7992e-07


