#!/bin/bash

nqa=7
nqp=25
nqu=54
tol=1e-6
eta=1.25
depth=5
order=8
nthreads=4

bin=../tools

gfile=wing-${nqp}.dat
mfile=matrix-wing-${nqp}-${nqu}-${order}-${depth}.dat

opts="-e ${tol} -a ${nqa} -u ${nqu} \
      -n ${eta} -d ${depth} -N ${order} \
      -m ${mfile} -g ${gfile}"
echo -- ${opts}

${bin}/nbi-surface -q ${nqp} -a wing.agg -o ${gfile}

${bin}/nbi-assemble-laplace ${opts} -T  ${nthreads}

${bin}/nbi-solve-laplace -f -m ${mfile} -g ${gfile} -D 4 -o 10 -d 2 \
      -t 1e-6 -r 50 -T ${nthreads} -b wsource.bc > wing-field.dat
