#!/bin/bash

k=1.3
nqa=7
nqp=54
nqu=85
tol=1e-6
eta=1.5
depth=5
order=8
nthreads=3

bin=../tools

gfile=Geometries/wing-${nqp}.dat
mfile=Matrices/matrix-wing-helmholtz-${nqp}-${nqu}-${order}-${depth}.dat

opts="-e ${tol} -a ${nqa} -u ${nqu} \
      -n ${eta} -d ${depth} -N ${order} \
      -m ${mfile} -g ${gfile} -k $k"
echo -- ${opts}

##${bin}/nbi-surface -q ${nqp} -a wing.agg -o ${gfile}

${bin}/nbi-assemble-helmholtz ${opts} -T ${nthreads}

${bin}/nbi-solve-helmholtz -m ${mfile} -g ${gfile} -D 5 -o 10 -d 2 -t 1e-6 \
      -f -T ${nthreads} -K ksp-options -P \
      -k ${k} -b wcsource.bc -s wing-field.dat 
