#!/bin/bash

## first argument is flag we want
flag=$1

## second argument is REAL or COMPLEX to set flags
if [ -z ${2+x} ]; then
    ## default is REAL
    scalar=_REAL
else
    scalar=_$2
fi

## third argument is architecture variable
if [ -z ${3+x} ]; then
    ## default is whatever PETSc gives us
    ##echo unset architecture
    echo
else
    arch=$3
fi

#if [ -z ${arch+x} ]; then
#    ## default is whatever PETSc gives us
#    make -f petsc-makefile 2>/dev/null > petsc-flags.tmp
#else
#    make PETSC_ARCH=$arch -f petsc-makefile 2>/dev/null >  petsc-flags.tmp
#fi
make -f petsc-makefile 2>/dev/null > petsc-flags.tmp
scalar=
sed -e 's/\"//g' \
    -e s/PETSC_CC_INCLUDES/PETSC_CC_INCLUDES${scalar}/ \
    -e s/PETSC_FLAGS/PETSC_FLAGS${scalar}/ \
    -e s/PETSC_LIB/PETSC_LIB${scalar}/ \
    petsc-flags.tmp | grep ${flag}
