#!/bin/bash

k=10
nqa=7
nqp=7
nqu=25
tol=1e-3
eta=1.25
depth=3
order=8
nthreads=4

## path to executables
bin=../../tools

## store geometry and matrix data in subdirectories
##gfile=Geometries/sphere-${nqp}.nbi
##mfile=Matrices/matrix-sphere-helmholtz-${nqp}-${nqu}-${order}-${depth}.dat
gfile=Geometries/wing-${nqp}.nbi
mfile=Matrices/matrix-wing-helmholtz-${nqp}-${nqu}-${order}-${depth}.dat
#gfile=Geometries/aircraft-${nqp}.nbi
#mfile=Matrices/matrix-aircraft-helmholtz-${nqp}-${nqu}-${order}-${depth}.dat

## generate the geometry from the GMSH input
${bin}/nbi-surface -q ${nqp} -m wing.geo -o ${gfile}
#${bin}/nbi-surface -q ${nqp} -m aircraft.geo -o ${gfile}

opts="-e ${tol} -a ${nqa} -u ${nqu} \
      -n ${eta} -d ${depth} -N ${order} \
      -m ${mfile} -g ${gfile} -k ${k}"
echo -- ${opts}

## assemble the problem matrices
${bin}/nbi-assemble-helmholtz ${opts} -T ${nthreads}

opts="-m ${mfile} -g ${gfile} -D 5 -o 10 -d 2 -t 1e-6 \
      -f -T ${nthreads} -K ksp-options \
      -k ${k} -b pcsource.bc -s solution.dat "
echo ${opts}

## solve with internal point source
${bin}/nbi-solve-helmholtz -m ${mfile} -g ${gfile} -D 5 -o 10 -d 2 -t 1e-3 \
      -f -T ${nthreads} \
      -k ${k} -b pcsource.bc -s solution.dat
#-K ksp-options -P \
## generate radiated field on 33x33 grid in plane z=2.5, -2 < x, y < 2
${bin}/nbi-surface -g grid-xy -d -2 -d -2 -d 2 -d 2 -d 2.5 \
      -i 33 -i 33 > grid.nbi
## field radiated by surface solution
${bin}/nbi-field-helmholtz -g ${gfile} -d solution.dat \
      -k ${k} -F grid.nbi > grid.dat
## generate gmsh files for visualization
${bin}/nbi-process -d grid.dat -g grid.nbi -r 2 > grid.msh

